import { defineArrayMember, defineField, defineType } from "sanity";

const activeAndOrder = [
  defineField({ name: "active", title: "게시", type: "boolean", initialValue: false }),
  defineField({ name: "order", title: "노출 순서", type: "number", initialValue: 0 }),
];

const siteSettings = defineType({
  name: "siteSettings",
  title: "사이트 설정",
  type: "document",
  fields: [
    defineField({ name: "brandName", title: "브랜드명", type: "string", initialValue: "ADS 아델슨", validation: (rule) => rule.required() }),
    defineField({ name: "brandNameEn", title: "영문 브랜드명", type: "string", initialValue: "ADS" }),
    defineField({ name: "legalCompanyName", title: "법인명", type: "string" }),
    defineField({ name: "manufacturerName", title: "제조사명", type: "string" }),
    defineField({ name: "salesCompanyName", title: "판매사명", type: "string" }),
    defineField({ name: "logo", title: "로고", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })] }),
    defineField({ name: "email", title: "이메일", type: "string" }),
    defineField({ name: "phone", title: "전화번호", type: "string" }),
    defineField({ name: "address", title: "주소", type: "string" }),
    defineField({ name: "inquiryLink", title: "견적 문의 링크", type: "string", initialValue: "#inquiry" }),
    defineField({ name: "catalogDocument", title: "최신 공개 카탈로그", type: "reference", to: [{ type: "downloadDocument" }] }),
    defineField({ name: "defaultSeoTitle", title: "기본 SEO 제목", type: "string" }),
    defineField({ name: "defaultSeoDescription", title: "기본 SEO 설명", type: "text", rows: 3 }),
  ],
});

const homePage = defineType({
  name: "homePage",
  title: "홈페이지",
  type: "document",
  fields: [
    defineField({
      name: "hero",
      title: "Hero",
      type: "object",
      fields: [
        defineField({ name: "title", title: "제목", type: "text", rows: 3 }),
        defineField({ name: "description", title: "설명", type: "text", rows: 3 }),
        defineField({ name: "desktopImage", title: "데스크톱 이미지 (16:9)", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })] }),
        defineField({ name: "mobileImage", title: "모바일 이미지 (4:5)", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })] }),
      ],
    }),
    defineField({ name: "overviewImage", title: "제품 개요 이미지 (4:3)", type: "image", options: { hotspot: true } }),
    defineField({ name: "processVideo", title: "제조공정 대표영상 URL", type: "url" }),
    defineField({ name: "processPoster", title: "제조공정 영상 썸네일", type: "image", options: { hotspot: true } }),
    defineField({ name: "productOverviewVideo", title: "제품 구조 및 특징 소개영상 URL", type: "url" }),
    defineField({ name: "productOverviewPoster", title: "제품 소개영상 썸네일", type: "image", options: { hotspot: true } }),
    defineField({ name: "companyOverviewVideo", title: "회사·생산 및 기술 소개영상 URL", type: "url" }),
    defineField({ name: "companyOverviewPoster", title: "회사 소개영상 썸네일", type: "image", options: { hotspot: true } }),
    defineField({ name: "verificationImage", title: "성능 시험 사진 (4:3)", type: "image", options: { hotspot: true } }),
    defineField({ name: "verificationReportThumbnail", title: "시험성적서 썸네일 (A4)", type: "image", options: { hotspot: true } }),
    defineField({ name: "sustainabilityStatementThumbnail", title: "탄소발자국 검증 성명서 썸네일", type: "image", options: { hotspot: true } }),
    defineField({ name: "featuredProducts", title: "대표 제품", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "product" }] })] }),
    defineField({ name: "featuredTests", title: "대표 성능 시험", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testResult" }] })] }),
    defineField({ name: "featuredTestVideos", title: "대표 성능 시연 영상", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testVideo" }] })] }),
    defineField({ name: "sectionOrder", title: "섹션 순서", type: "array", of: [defineArrayMember({ type: "string", options: { list: ["hero", "risks", "overview", "process", "productOverviewVideo", "verification", "performanceVideos", "benefits", "products", "preApplication", "applications", "sustainability", "documents", "company", "companyOverviewVideo", "catalog", "contact"] } })] }),
    defineField({
      name: "sectionVisibility",
      title: "섹션 공개 설정",
      type: "array",
      of: [defineArrayMember({
        type: "object",
        fields: [
          defineField({ name: "section", title: "섹션 키", type: "string", options: { list: ["hero", "risks", "overview", "process", "productOverviewVideo", "verification", "performanceVideos", "benefits", "products", "preApplication", "applications", "sustainability", "documents", "company", "companyOverviewVideo", "catalog", "contact"] }, validation: (rule) => rule.required() }),
          defineField({ name: "visible", title: "공개", type: "boolean", initialValue: true }),
        ],
      })],
    }),
  ],
});

const product = defineType({
  name: "product",
  title: "제품",
  type: "document",
  fields: [
    defineField({ name: "nameKo", title: "국문 제품명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "nameEn", title: "영문 제품명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "nameEn" }, validation: (rule) => rule.required() }),
    defineField({ name: "series", title: "시리즈", type: "string" }),
    defineField({ name: "productType", title: "유형", type: "string" }),
    defineField({ name: "summary", title: "요약", type: "text", rows: 3, validation: (rule) => rule.required() }),
    defineField({ name: "description", title: "상세 설명", type: "array", of: [defineArrayMember({ type: "block" })] }),
    defineField({ name: "gallery", title: "제품 이미지 (4:3)", type: "array", of: [defineArrayMember({ type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })] })] }),
    defineField({ name: "drawing", title: "도면", type: "file" }),
    defineField({ name: "sizes", title: "규격", type: "array", of: [defineArrayMember({ type: "string" })] }),
    defineField({ name: "ratedDynamicLoad", title: "제조사 제시 동적하중", type: "string" }),
    defineField({ name: "ratedStaticLoad", title: "제조사 제시 정적하중", type: "string" }),
    defineField({ name: "weight", title: "제품 중량", type: "string" }),
    defineField({ name: "forkEntry", title: "포크 진입 방향", type: "string" }),
    defineField({ name: "applications", title: "제조사 제시 적용 용도", type: "array", of: [defineArrayMember({ type: "string" })] }),
    defineField({ name: "relatedTests", title: "관련 시험", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testResult" }] })] }),
    defineField({ name: "relatedVideos", title: "관련 영상", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testVideo" }] })] }),
    defineField({ name: "relatedCases", title: "관련 사례", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "caseStudy" }] })] }),
    defineField({ name: "disclaimer", title: "주의문구", type: "text", rows: 3 }),
    ...activeAndOrder,
  ],
  preview: { select: { title: "nameKo", subtitle: "series", media: "gallery.0" } },
});

const testResult = defineType({
  name: "testResult",
  title: "성능 시험",
  type: "document",
  fields: [
    defineField({ name: "title", title: "시험자료명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "testType", title: "시험 유형", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "classification", title: "자료 구분", type: "string", options: { list: ["공인시험", "의뢰시험", "사내시연"] }, validation: (rule) => rule.required() }),
    defineField({ name: "organization", title: "시험기관", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "reportNumber", title: "보고서 번호", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "issueDate", title: "발급일", type: "date" }),
    defineField({ name: "testPeriod", title: "시험기간", type: "string" }),
    defineField({ name: "clientManufacturer", title: "의뢰자·제조사 (원문)", type: "string" }),
    defineField({ name: "testDate", title: "시험일", type: "date", validation: (rule) => rule.required() }),
    defineField({ name: "productModel", title: "적용 모델", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "specimenSize", title: "시료 규격", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "sampleQuantity", title: "시료 수량", type: "string" }),
    defineField({ name: "productionBatch", title: "생산 배치", type: "string" }),
    defineField({ name: "standard", title: "시험방법·표준", type: "string" }),
    defineField({ name: "environment", title: "시험 환경", type: "text", rows: 3 }),
    defineField({ name: "results", title: "시험 결과", type: "array", validation: (rule) => rule.required().min(1), of: [defineArrayMember({ type: "object", fields: [defineField({ name: "name", title: "시험명", type: "string", validation: (rule) => rule.required() }), defineField({ name: "value", title: "시험값", type: "string", validation: (rule) => rule.required() }), defineField({ name: "referenceValue", title: "기준값", type: "string" }), defineField({ name: "judgement", title: "판정", type: "string" })] })] }),
    defineField({ name: "reportFile", title: "시험성적서 PDF", type: "file", validation: (rule) => rule.required() }),
    defineField({ name: "thumbnail", title: "문서 썸네일", type: "image" }),
    defineField({ name: "accreditationScope", title: "인정범위 메모", type: "text", rows: 2 }),
    defineField({ name: "publicDisclosure", title: "공개 허용", type: "boolean", initialValue: false }),
    defineField({ name: "disclaimer", title: "주의문구", type: "text", rows: 3 }),
    defineField({ name: "active", title: "게시", type: "boolean", initialValue: false }),
  ],
});

const testVideo = defineType({
  name: "testVideo",
  title: "성능 시연 영상",
  type: "document",
  fields: [
    defineField({ name: "title", title: "영상명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "titleEn", title: "영문 영상명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "originalFileName", title: "원본 파일명", type: "string" }),
    defineField({ name: "category", title: "시연 유형", type: "string", options: { list: ["heavy-load", "vehicle-load", "flame-exposure", "drop-impact", "compression-load", "immersion"] }, validation: (rule) => rule.required() }),
    defineField({ name: "durationSeconds", title: "영상 길이(초)", type: "number", validation: (rule) => rule.required().positive() }),
    defineField({ name: "videoSource", title: "영상 출처", type: "string", options: { list: [{ title: "제조사", value: "manufacturer" }] }, initialValue: "manufacturer", validation: (rule) => rule.required() }),
    defineField({ name: "videoClassification", title: "영상 구분", type: "string", options: { list: [{ title: "시연", value: "demonstration" }] }, initialValue: "demonstration", validation: (rule) => rule.required() }),
    defineField({ name: "isStandardizedTest", title: "표준화 시험 여부", type: "boolean", initialValue: false, readOnly: true }),
    defineField({ name: "streamId", title: "Cloudflare Stream ID", type: "string" }),
    defineField({ name: "externalUrl", title: "외부 영상 URL", type: "url" }),
    defineField({ name: "poster", title: "썸네일 (16:9)", type: "image" }),
    defineField({ name: "description", title: "설명", type: "text", rows: 3, validation: (rule) => rule.required() }),
    defineField({ name: "productModels", title: "관련 제품", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "product" }] })] }),
    defineField({ name: "dimensions", title: "시료 규격", type: "string" }),
    defineField({ name: "palletWeight", title: "팔레트 중량", type: "string" }),
    defineField({ name: "appliedLoad", title: "적용 하중", type: "string" }),
    defineField({ name: "vehicleWeight", title: "차량 중량", type: "string" }),
    defineField({ name: "dropHeight", title: "낙하 높이", type: "string" }),
    defineField({ name: "dropCount", title: "낙하 횟수", type: "number" }),
    defineField({ name: "immersionDuration", title: "침수 시간", type: "string" }),
    defineField({ name: "flameSource", title: "화염원", type: "string" }),
    defineField({ name: "flameTemperature", title: "화염 온도", type: "string" }),
    defineField({ name: "flameDistance", title: "화염 거리", type: "string" }),
    defineField({ name: "flameExposureDuration", title: "화염 노출시간", type: "string" }),
    defineField({ name: "testAuthority", title: "자료 제공 주체", type: "string", initialValue: "제조사 제공 시연자료", validation: (rule) => rule.required() }),
    defineField({ name: "relatedReports", title: "관련 시험자료", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testResult" }] })] }),
    defineField({ name: "resultSummary", title: "결과 요약", type: "text", rows: 3 }),
    defineField({ name: "limitations", title: "한계", type: "text", rows: 3 }),
    defineField({ name: "disclaimer", title: "주의문구", type: "text", rows: 3, validation: (rule) => rule.required() }),
    ...activeAndOrder,
  ],
});

const industry = defineType({
  name: "industry",
  title: "적용 분야",
  type: "document",
  fields: [
    defineField({ name: "title", title: "분야명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "description", title: "설명", type: "text", rows: 2, validation: (rule) => rule.required() }),
    defineField({ name: "iconName", title: "Lucide 아이콘명", type: "string", options: { list: ["FlaskConical", "Package", "Cylinder", "Warehouse", "Container", "Boxes"] }, validation: (rule) => rule.required() }),
    ...activeAndOrder,
  ],
});

const caseStudy = defineType({
  name: "caseStudy",
  title: "적용 사례",
  type: "document",
  fields: [
    defineField({ name: "title", title: "사례명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "clientDisplayName", title: "고객 표시명", type: "string" }),
    defineField({ name: "clientDisclosure", title: "고객 공개 동의", type: "boolean", initialValue: false }),
    defineField({ name: "industry", title: "적용 분야", type: "reference", to: [{ type: "industry" }] }),
    defineField({ name: "cargoType", title: "화물 종류", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "loadPerPallet", title: "팔레트당 하중", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "product", title: "적용 제품", type: "reference", to: [{ type: "product" }], validation: (rule) => rule.required() }),
    defineField({ name: "environment", title: "사용 환경", type: "text", rows: 3 }),
    defineField({ name: "problem", title: "검토 과제", type: "text", rows: 3 }),
    defineField({ name: "solution", title: "적용 내용", type: "text", rows: 3 }),
    defineField({ name: "result", title: "확인 결과", type: "text", rows: 3 }),
    defineField({ name: "images", title: "사례 이미지", type: "array", of: [defineArrayMember({ type: "image", fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })] })] }),
    defineField({ name: "videos", title: "관련 영상", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "testVideo" }] })] }),
    defineField({ name: "featured", title: "대표 사례", type: "boolean", initialValue: false }),
    ...activeAndOrder,
  ],
});

const downloadDocument = defineType({
  name: "downloadDocument",
  title: "시험·인증 문서 / 카탈로그",
  type: "document",
  fields: [
    defineField({ name: "title", title: "문서명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "documentType", title: "문서 유형", type: "string", options: { list: ["카탈로그", "제품 성능 시험", "포름알데히드 시험", "탄소발자국 검증", "세관·수출", "SDS", "FSC CoC", "적합성 확인서", "특허·기술자료"] }, validation: (rule) => rule.required() }),
    defineField({ name: "version", title: "버전", type: "string" }),
    defineField({ name: "language", title: "언어", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "file", title: "파일", type: "file", validation: (rule) => rule.required() }),
    defineField({ name: "thumbnail", title: "A4 썸네일", type: "image", validation: (rule) => rule.required() }),
    defineField({ name: "issueDate", title: "발급일", type: "date" }),
    defineField({ name: "expiryDate", title: "유효기간", type: "date" }),
    defineField({ name: "issuer", title: "발급기관", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "reportNumber", title: "문서 번호", type: "string" }),
    defineField({ name: "relatedProducts", title: "적용 제품", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "product" }] })] }),
    defineField({ name: "pageCount", title: "페이지 수", type: "number" }),
    defineField({ name: "fileSize", title: "표시용 파일 크기", type: "string" }),
    defineField({ name: "publicDownload", title: "다운로드 공개", type: "boolean", initialValue: false }),
    defineField({ name: "publicPreview", title: "메타데이터·미리보기 공개", type: "boolean", initialValue: false }),
    defineField({ name: "previewAvailable", title: "파일 미리보기 허용", type: "boolean", initialValue: false }),
    defineField({ name: "featured", title: "최신/대표 문서", type: "boolean", initialValue: false }),
    defineField({ name: "active", title: "게시", type: "boolean", initialValue: false }),
  ],
});

const companyGallery = defineType({
  name: "companyGallery",
  title: "회사·공장",
  type: "document",
  fields: [
    defineField({ name: "title", title: "제목", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "category", title: "분류", type: "string", options: { list: ["공장 전경", "생산설비", "R&D", "품질검사", "기타"] }, validation: (rule) => rule.required() }),
    defineField({ name: "image", title: "실제 이미지", type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "대체 텍스트", type: "string", validation: (rule) => rule.required() })], validation: (rule) => rule.required() }),
    defineField({ name: "caption", title: "설명", type: "text", rows: 2 }),
    defineField({ name: "location", title: "위치", type: "string" }),
    ...activeAndOrder,
  ],
});

const companyMetric = defineType({
  name: "companyMetric",
  title: "회사 지표",
  type: "document",
  fields: [
    defineField({ name: "label", title: "지표명", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "value", title: "수치", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "unit", title: "단위", type: "string" }),
    defineField({ name: "sourceType", title: "출처 유형", type: "string", initialValue: "companyProvided" }),
    defineField({ name: "sourceDocument", title: "출처 문서", type: "file" }),
    defineField({ name: "applicableLegalEntity", title: "기준 법인", type: "string" }),
    defineField({ name: "verified", title: "확인 완료", type: "boolean", initialValue: false }),
    ...activeAndOrder,
  ],
});

export const schemaTypes = [
  siteSettings,
  homePage,
  product,
  testResult,
  testVideo,
  industry,
  caseStudy,
  downloadDocument,
  companyGallery,
  companyMetric,
];
