// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5kHY8QCsz8z2XtVIg2zROJ6mZMLpYACE',
    appId: '1:58433730288:web:601a7e65dea100d05cf435',
    messagingSenderId: '58433730288',
    projectId: 'ads-inquiry',
    authDomain: 'ads-inquiry.firebaseapp.com',
    storageBucket: 'ads-inquiry.firebasestorage.app',
    measurementId: 'G-YLLXHGHQR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2x0VylWrgNI8n2LMtEH7aNfX0y3ZiGU',
    appId: '1:58433730288:android:404e3cbcfe1158575cf435',
    messagingSenderId: '58433730288',
    projectId: 'ads-inquiry',
    storageBucket: 'ads-inquiry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQUmzUxge9E45ZRB82RCmW8PGt_S5jtc',
    appId: '1:58433730288:ios:83d2057fb5ab56d05cf435',
    messagingSenderId: '58433730288',
    projectId: 'ads-inquiry',
    storageBucket: 'ads-inquiry.firebasestorage.app',
    iosBundleId: 'com.example.adsInquiryAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQUmzUxge9E45ZRB82RCmW8PGt_S5jtc',
    appId: '1:58433730288:ios:83d2057fb5ab56d05cf435',
    messagingSenderId: '58433730288',
    projectId: 'ads-inquiry',
    storageBucket: 'ads-inquiry.firebasestorage.app',
    iosBundleId: 'com.example.adsInquiryAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5kHY8QCsz8z2XtVIg2zROJ6mZMLpYACE',
    appId: '1:58433730288:web:0dbae2ff83990dcf5cf435',
    messagingSenderId: '58433730288',
    projectId: 'ads-inquiry',
    authDomain: 'ads-inquiry.firebaseapp.com',
    storageBucket: 'ads-inquiry.firebasestorage.app',
    measurementId: 'G-6PQM8J7C9P',
  );
}
